In [2]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm, t, chi2

In [3]:
n = 100
xn = np.array([49, 55, 53])
s = np.array([8.2, 10.1, 7.5])

In [4]:
alpha = 0.05
errore_mu = s*t.ppf(1-0.5*alpha, n-1)/np.sqrt(n)
print(errore_mu)

[1.6270579  2.00405912 1.48816271]


In [5]:
xmin = xn - errore_mu
xmax = xn + errore_mu
print(xmin)
print(xmax)

[47.3729421  52.99594088 51.51183729]
[50.6270579  57.00405912 54.48816271]


In [6]:
#Osservando i dati, l'ultimo campione è molto migliore del primo
#Non serve che siano distribuite normalmente perché n > 30