In [1]:
import numpy as np
P = np.array([[0, 1/3, 0, 1/3, 1/3],[1/3, 0, 1/3, 0, 1/3],[0, 1/3, 0, 1/3, 1/3],
             [1/3, 0, 1/3, 0, 1/3], [1/4, 1/4, 1/4, 1/4, 0]])
display(P)

#metodo analitico
lam ,V = np.linalg.eig(P.T)
display(lam)
display(V)

array([[0.        , 0.33333333, 0.        , 0.33333333, 0.33333333],
       [0.33333333, 0.        , 0.33333333, 0.        , 0.33333333],
       [0.        , 0.33333333, 0.        , 0.33333333, 0.33333333],
       [0.33333333, 0.        , 0.33333333, 0.        , 0.33333333],
       [0.25      , 0.25      , 0.25      , 0.25      , 0.        ]])

array([ 1.00000000e+00, -1.29122935e-16, -6.66666667e-01, -3.33333333e-01,
        0.00000000e+00])

array([[-4.16025147e-01, -7.07106781e-01,  5.00000000e-01,
        -2.23606798e-01,  2.01454444e-02],
       [-4.16025147e-01,  6.17628897e-17, -5.00000000e-01,
        -2.23606798e-01, -7.06819751e-01],
       [-4.16025147e-01,  7.07106781e-01,  5.00000000e-01,
        -2.23606798e-01, -2.01454444e-02],
       [-4.16025147e-01,  2.28296343e-16, -5.00000000e-01,
        -2.23606798e-01,  7.06819751e-01],
       [-5.54700196e-01,  4.15560011e-17,  5.69175284e-17,
         8.94427191e-01,  7.74775310e-17]])

In [3]:
v = np.real(V[:,0])/np.sum(np.real(V[:,0]))
display(v)

array([0.1875, 0.1875, 0.1875, 0.1875, 0.25  ])

In [9]:
#metodo monte carlo

n = 5
F = np.zeros(n)
j = np.random.randint(n)
F[j] = 1
N = 1000000

for i in range(N):
    j_multi = np.random.multinomial(1,P[j,:])
    j = np.nonzero(j_multi)[0][0]
    F[j] = F[j]+1

vv = F/N
display(vv)

array([0.187455, 0.187014, 0.187546, 0.187334, 0.250652])