In [1]:
# Punto 1) matrice di transizione
import numpy as np

matrix1 = np.array([["0", "p", "1-p"], ["1-p", "0", "p"], ["p", "1-p", "0"]])
print (matrix1)

[['0' 'p' '1-p']
 ['1-p' '0' 'p']
 ['p' '1-p' '0']]


In [2]:
# Punto 2) fissato p = 1/3, mostrare che è una catena regolare
p = 1/3
P = np.array([[0, p, 1-p], [1-p, 0, p], [p, 1-p, 0]])
print(P)

print(" ")

matrix3 = np.dot(P, P)
print(matrix3)
print("siccome tutti gli archi sono > 0 allora la catena è regolare")

[[0.         0.33333333 0.66666667]
 [0.66666667 0.         0.33333333]
 [0.33333333 0.66666667 0.        ]]
 
[[0.44444444 0.44444444 0.11111111]
 [0.11111111 0.44444444 0.44444444]
 [0.44444444 0.11111111 0.44444444]]
siccome tutti gli archi sono > 0 allora la catena è regolare


In [3]:
# Punto 3) Fissato p = 1/3 determinare la distribuzione stazionaria

# metodo 1: v = vP
lam, V = np.linalg.eig(P.T)
print("lam:", lam)
print(" ")
print("V:", V)

print(" ")

v = np.real(V[:, 0]) / np.sum(np.real(V[:, 0]))
print("v:", v)

lam: [ 1. +0.j         -0.5+0.28867513j -0.5-0.28867513j]
 
V: [[ 0.57735027+0.j   0.57735027+0.j   0.57735027-0.j ]
 [ 0.57735027+0.j  -0.28867513+0.5j -0.28867513-0.5j]
 [ 0.57735027+0.j  -0.28867513-0.5j -0.28867513+0.5j]]
 
v: [0.33333333 0.33333333 0.33333333]
