In [1]:
import numpy as np
from scipy.stats import chi2

n = 170
X = np.array([[44,10],[81,35]])

#prob empiriche trattamento
p = np.array([54,116])/n

q = np.array([125,45])/n

display(p)
display(q)

array([0.31764706, 0.68235294])

array([0.73529412, 0.26470588])

In [3]:
#prob congiunta empirica

pi = X/n
display(pi)

array([[0.25882353, 0.05882353],
       [0.47647059, 0.20588235]])

In [5]:
T = 0

for h in range(2):
    for k in range(2):
        T = T + ((p[h]*q[k] - pi[h][k])**2)/pi[h][k]

T = n*T
display(T)

3.0175117739708286

In [7]:
alpha = 0.05
chi = chi2.ppf(1-alpha,1)
display(chi)

3.841458820694124